services:
  bird:
    build:
      context: .
      dockerfile: docker/bird/Dockerfile
    container_name: crowdsec-bird
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - bird_runtime:/run/bird
      - bird_dynamic:/etc/bird/dynamic

  bouncer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crowdsec-bird-bouncer
    restart: unless-stopped
    network_mode: host
    depends_on:
      - bird
    env_file:
      - ./docker/full/bird-bouncer.env
    volumes:
      - bird_runtime:/run/bird
      - bird_dynamic:/etc/bird/dynamic

volumes:
  bird_runtime:
  bird_dynamic:

